name: logos_messenger
description: "Logos Messenger - Secure and Private Messaging App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  google_fonts: ^5.0.0
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.2.4
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  local_auth: ^3.0.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4


# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    #- assets/fonts/
    - assets/secrets.env

flutter_native_splash:
  color: "#1A2235"
  image: assets/images/logo2.png
  android: true
  ios: true
  web: false

flutter_launcher_icons:
  image_path: "assets/images/icon2.png"
  android: true
  ios: true
